// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Perzam1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://192.168.122.182:4444/wd/hub"), DesiredCapabilities.firefox());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void perzam1() {
    // Test name: perzam1
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://www.perzam.com.co/");
    // 2 | setWindowSize | 550x692 | 
    driver.manage().window().setSize(new Dimension(550, 692));
    // 3 | click | linkText=IBM installation manager | 
    driver.findElement(By.linkText("IBM installation manager")).click();
    // 4 | selectFrame | index=0 | 
    driver.switchTo().frame(0);
    // 5 | click | css=.ytp-large-play-button | 
    driver.findElement(By.cssSelector(".ytp-large-play-button")).click();
    // 6 | click | css=.ytp-play-button | 
    driver.findElement(By.cssSelector(".ytp-play-button")).click();
  }
}
